name: publish

on:
  push:
    paths:
      - RP5.API\**
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github_actor}}/rp5-zigbee-api:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }}
        --password-stdin  
    - name: Build and publish
      run: |
        docker Build . --tag ${{ envv.REGISTRY }}/${{ env.IMAGE_NAME }}
        docker push ${{ envv.REGISTRY }}/${{ env.IMAGE_NAME }}